export const CREATE_FEEDBACK = 'CREATE_FEEDBACK';
export const UPDATE_FEEDBACK = 'UPDATE_FEEDBACK';
export const DELETE_FEEDBACK = 'DELETE_FEEDBACK';
export const FIND_ALL_FEEDBACK = 'FIND_ALL_FEEDBACK';
export const FIND_ONE_FEEDBACK = 'FIND_ONE_FEEDBACK';
export const GET_PROJECT = 'GET_PROJECT';
export const ENQUEUE_FEEDBACK = 'ENQUEUE_FEEDBACK';