export const ENQUEUE_GENERATE_INSIGHTS = 'ENQUEUE_GENERATE_INSIGHTS';
export const GET_INSIGHTS_JOB_STATUS = 'GET_INSIGHTS_JOB_STATUS';
export const CANCEL_INSIGHTS_JOB = 'CANCEL_INSIGHTS_JOB';

export const GET_FEEDBACK_FOR_INSIGHTS = 'GET_FEEDBACK_FOR_INSIGHTS';
export const GET_EXISTING_INSIGHTS = 'GET_EXISTING_INSIGHTS';

export const SAVE_INSIGHTS = 'SAVE_INSIGHTS';
